DOCKER_VERSION = 26.1.2
DOCKER_COMPOSE_VERSION = 2.27.0

build:
	docker build -t dcind \
		--build-arg DOCKER_VERSION=${DOCKER_VERSION} \
		--build-arg DOCKER_COMPOSE_VERSION=${DOCKER_COMPOSE_VERSION} \
		.
