# This pipeline publishes and keeps the dcind image up to date

resources:
- name: docker-release
  type: github-release
  icon: github
  check_every: 6h
  source:
    owner: moby
    repository: moby
    access_token: ((ci-gh-public-repo-read-token))

- name: docker-compose-release
  type: github-release
  icon: github
  check_every: 6h
  source:
    owner: docker
    repository: compose
    access_token: ((ci-gh-public-repo-read-token))

- name: repo
  type: git
  icon: git
  check_every: 30m
  source:
    uri: https://github.com/emjot/dcind
    ignore_paths: [pipeline.yml, README.md]

- name: weekly-rebuild
  type: time
  icon: clock
  source:
    days:
      - Thursday
    start: 3:00 AM
    stop: 3:30 AM
    location: Europe/Berlin
    initial_version: true

- name: dcind
  icon: docker
  type: registry-image
  source:
    repository: emjotde/dcind
    tag: latest
    username: ((docker.username))
    password: ((docker.password))

jobs:
- name: build-and-publish
  plan:
  - in_parallel:
    - get: docker-release
      params:
        globs: [none]
    - get: docker-compose-release
      params:
        globs: [none]
    - get: repo
      trigger: true
    - get: weekly-rebuild
      trigger: true
  - in_parallel:
    - load_var: docker-version
      file: docker-release/version
    - load_var: docker-compose-version
      file: docker-compose-release/version
  - task: build-image
    privileged: true
    params:
      BUILD_ARG_DOCKER_VERSION: ((.:docker-version))
      BUILD_ARG_DOCKER_COMPOSE_VERSION: ((.:docker-compose-version))
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: repo
        path: .
      outputs:
      - name: image
      run:
        path: build
  - task: tags
    params:
      DOCKER_VERSION: ((.:docker-version))
    config:
      platform: linux
      image_resource:
        type: mock
        source:
          mirror_self: true
      outputs:
      - name: tags
      run:
        path: sh
        args:
          - -c
          - |
            echo "${DOCKER_VERSION} ${DOCKER_VERSION}-$(date +%Y%m%d)" > tags/tags
  - put: dcind
    inputs: detect
    params:
      image: image/image.tar
      additional_tags: tags/tags
